### ISSUE TITLE
administrate:views generator is missing

### ISSUE THREAD

**Issue by fahidqbx** [thoughtbot/administrate#215]
I am trying to customize the views. but when I run the command
`rails generate administrate:views User`
is shows the error
```
Could not find generator 'administrate:views'. Maybe you meant 
'administrate:install' or 'kaminari:views' or 'devise:views'
Run `rails generate --help` for more options.
```

and running the `rails generate --help`
giving me only two generators of administrate
```
administrate:dashboard
administrate:install
```

Anybody fixed or facing this issue.?

**Comment by itsSaad** [comment]
im getting this same issue as well

**Comment by 5minpause** [comment]
Could you offer some insight into your setup? *What do I need to reproduce this?*
What's your Rails and Ruby versions?

**Comment by leewaa** [comment]
Rails `4.2.4`
Ruby `2.1.5`

**Comment by 5minpause** [comment]
I can't seem to reproduce this problem:

```
admin-test % rake db:create
admin-test % rails generate devise:install
      create  config/initializers/devise.rb
      create  config/locales/devise.en.yml
===============================================================================

Some setup you must do manually if you haven't yet:

  1. Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  4. If you are deploying on Heroku with Rails 3.2 only, you may want to set:

       config.assets.initialize_on_precompile = false

     On config/application.rb forcing your application to not access the DB
     or load models when precompiling your assets.

  5. You can copy Devise views (for customization) to your app by running:

       rails g devise:views

===============================================================================
admin-test % rails g controller welcome index
      create  app/controllers/welcome_controller.rb
       route  get 'welcome/index'
      invoke  erb
      create    app/views/welcome
      create    app/views/welcome/index.html.erb
      invoke  test_unit
      create    test/controllers/welcome_controller_test.rb
      invoke  helper
      create    app/helpers/welcome_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/welcome.coffee
      invoke    scss
      create      app/assets/stylesheets/welcome.scss
admin-test % rails generate devise AdminUser
      invoke  active_record
      create    db/migrate/20151111094946_devise_create_admin_users.rb
      create    app/models/admin_user.rb
      invoke    test_unit
      create      test/models/admin_user_test.rb
      create      test/fixtures/admin_users.yml
      insert    app/models/admin_user.rb
       route  devise_for :admin_users
admin-test % rails generate administrate:views AdminUser
      create  app/views/admin/admin_users/index.html.erb
      create  app/views/admin/admin_users/_collection.html.erb
      create  app/views/admin/admin_users/show.html.erb
      create  app/views/admin/admin_users/new.html.erb
      create  app/views/admin/admin_users/_form.html.erb
      create  app/views/admin/admin_users/edit.html.erb
   identical  app/views/admin/admin_users/_form.html.erb
admin-test %
```

I pushed my sample app to Github, perhaps that helps? https://github.com/5minpause/admin-test
I used `ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]` and Rails 4.2.4

**Comment by fahidqbx** [comment]
@5minpause I have 
`ruby 2.1.5 p273`
`rails 4.2.0`

and I configured the devise with 2 modules [Admins, Users]

I am not getting the views generator for the administrate.

can I add the views generator manually.?

**Comment by graysonwright** [comment]
@fahidqbx @itsSaad what version of Administrate are you using? Can you try using

```ruby
gem "administrate", "~> 0.1.0"
```

in your Gemfile and seeing if the generator becomes available?

**Comment by fahidqbx** [comment]
@graysonwright 
I updated the version to `~> 0.1.0`.
but views generator is still missing.

My configuration is:
`devise` with 2 models [User, Admin]
`devise_invitable`
and `administrate`

**Comment by graysonwright** [comment]
@fahidqbx can you share your project's code on github?

Also, can you run this command and paste the output?

```
ls $(gem env | grep "INSTALLATION DIRECTORY" | sed "s/^.*: //")/gems/administrate*/lib/generators/administrate/**/*.rb
```

**Comment by graysonwright** [comment]
@fahidqbx It looks like this issue is going a bit stale. Can you give a status update?
